providers:
  lxd:
    enable: true
  k8s:
    enable: true
    bootstrap: false
    bootstrap-constraints:
      root-disk: "2G"
    features:
      load-balancer:
        l2-mode: "true"
        cidrs: "10.43.45.0/28"
      local-storage: {}
      network: {}

host:
  packages:
    - gnome-keyring
    - python3-pip
    - python3-venv
  snaps:
    charmcraft:
    jq:
    yq:
    rockcraft: