juju:
  # TODO: revert this back to 4.1/stable
  channel: 4.1/edge
  model-defaults:
    test-mode: "true"
    automatically-retry-hooks: "true"

providers:
  lxd:
    enable: true
    bootstrap: false
